version: "3.7"
services:

  mariadb:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql:z
    env_file:
      - .env
    restart: always

  ianseo:
    image: arqueria/ianseo
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb

