version: "3.7"
services:

  ianseodb:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql:z
      - ./initdb.d:/docker-entrypoint-initdb.d:z
    env_file:
      - .env
    restart: always

  ianseo:
    image: arqueria/ianseo
    volumes:
      - ./src:/var/www/html:z
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb

