<?php
$lang['AutoImportSettings']='<b> Hanya untuk Pengguna Pakar </b> <br> Mengubah tingkah laku lalai akan menghasilkan hasil yang tidak tepat. <br> Penting untuk mengira semula semua peringkat yang telah disiapkan sebagai "manual" SEBELUM mengirim ke ianseo.net atau hasil percetakan dan secara umum sebelum setiap pengedaran dalam bentuk apa pun.';
$lang['ChangeComponents']='<p>Untuk meneruskan perubahan, hapus atlet yang tidak ada dalam pasukan lagi untuk mengaktifkan pilihan yang mungkin.</p>&#9654&nbsp;Skor termasuk dalam jumlah pusingan kelayakan pasukan<br>&#9655&nbsp;Markah tidak termasuk dalam jumlah pusingan kelayakan pasukan';
$lang['GetBarcodeSeparator']='Selepas mencetak helaian rujukan kodbar, baca kodbar«JARAK» untuk mengaktifkan item pembaca yang betul.';
$lang['HomePage']='Ini adalah halaman di mana anda boleh memilih atau mencipta kejohanan.';
$lang['ISK-LockedSessionHelp']='Ikon {$a} menunjukkan jika aplikasi boleh mendapat skor atau tidak dalam sesi tersebut.';
$lang['ISK-ServerUrlPin']='<b> JANGAN KONGSI NOMBOR INI </b> <br> Gunakan PIN pilihan anda (4 Angka Angka) untuk digunakan untuk memasuki pertandingan anda. <br> Peranti boleh mendapat markah dalam pertandingan anda hanya membaca QR-Code yang dicetak oleh IANSEO. <br> Sekiranya terdapat input manual dalam aplikasi Ianseo Scorekeeper LITE, kod Pertandingan yang akan digunakan adalah<b>{$ a}</b>';
$lang['ScoreBarCodeShortcuts']='Baca kod bar yang dicetak pada kad skor. <br/> Memasukkan secara manual # diikuti dengan nama atlet mencari pangkalan data untuk mencari atlet tersebut <br/>Memasukkan @ diikuti oleh carian sasaran sasaran untuk sasaran itu. Jarak HARUS ditetapkan. Sesi sepatutnya dinyatakan (digit pertama) dan sasaran adalah 0-empuk hingga 3 digit.';
$lang['TV-ChannelSetup']='= Persediaan Saluran = Setelah menyiapkan saluran anda seperti yang dikehendaki, sambungkan penyemak imbas peranti yang hendak dihubungkan ke saluran ke <code> http: //IP.OF.IANSEO/tv.php? Id = CHANNEL </ code> di mana \'\' \'IP.OF.IANSEO\' \'\' adalah IP di mana ianseo sedang berjalan (termasuk direktori jika ada) dan \'\' \'CHANNEL\' \'\' adalah ID saluran';
$lang['TV-RotEdit']='<div> Halaman pembentangan dibuat sekurang-kurangnya satu halaman kandungan. </ div> <div> Halaman kandungan akan dipaparkan satu demi satu dan mulakan semula. </ div> <div> <b> NOTA: </ b> dalam enjin versi biasa dan cahaya, kandungan pertama sekali lagi ditunjukkan sebagai yang terakhir, jadi bijak untuk memasukkan sebagai kandungan pertama sebuah gambar (logo persaingan misalnya). </ div> <div> Kandungan boleh sama ada berdasarkan persaingan (senarai permulaan, kelayakan, padanan ...) atau "multimedia" (imej, mesej HTML, ...). </ div>';
$lang['TV-RotEdit-DB']='<h2> Pengurusan CSS3 (Enjin lanjutan) </ h2> <h3> Panjang Panjang </ h3> <ul> <li> <b> rem: </ b> <b> em: </ b> dari karakter semasa </ li> <li> <b> mantan: </ b> b> lebar nombor "0" </ li> <li> <b> vh: </ b> 1/100 ketinggian skrin </ li> <li> <b> 1/100 lebar skrin </ li> <li> <b> vmin: </ b> 1 / ke-100 dari nilai minimum antara ketinggian dan lebar skrin </ li> <li> <b > vmax: </ b> 1/100 nilai maksimum antara ketinggian dan lebar skrin </ li> </ ul> <h3> Kotak Fleksibel </ h3> <li> <b> / b> <ul> <li> <b> A </ b>: jika 0 bermaksud kotak tidak dapat berkembang; jika> 1 bermakna kotak boleh berkembang pada "kelajuan" berbanding kotak lain (jika kotak 1 mempunyai 2 dan kotak 2 mempunyai 3, kotak 2 akan mengembangkan 1.5 lebih daripada kotak 1 yang seterusnya akan expan sebanyak dua kali sebagai kotak dengan nilai ini ditetapkan kepada 1) </ li> <li> <b> B: </ b> jika 0 kotak tidak dapat mengecut; jika 1 kotak boleh mengecilkan </ li> <li> <b> C: </ b> pemisahan awal kotak </ li> </ ul> </ li> <h3> rujukan CSS </ h3> <a href = "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference"> https://developer.mozilla.org/en-US/docs/Web/CSS/Reference </a>';
$lang['TV-RotList']='<div>Ini adalah senarai halaman persembahan yang tersedia untuk dihantar ke videowall, moitors atau siaran.</div><div>3 enjin berbeza disediakan, klik pada pautan untuk mengaktifkan:</div><ul><li>enjin biasa yang serasi dengan kebanyakan penyemak imbas</li><li>enjin versi cahaya yang serasi dengan kebanyakan penyemak imbas tetapi menggunakan sumber yang kurang</li><li>versi lanjutan yang menggunakan pelayar moden keupayaan HTML5</li></ul><div>Untuk membuat kandungan baru, masukkan nama untuk itu dan tekan butang.</div>';
?>