<?php
$lang['AutoImportSettings']='<b>Solo per Utenti Esperti</b><br>Cambiare i parametri di default può portare ad avere risultati non precisi.<br> E\' importante ricalcolare tutte le rank degli eventi che sono stati impostati manualmente PRIMA di inviare i risultati a ianseo.net o stampare i risultati e, in generale, sempre prima di fare qualsiasi tipo di distribuzione.';
$lang['ChangeComponents']='<p>Per procedere con un cambio di componente, prima togliere l\'atleta che non è più nel team in modo da poter attivare le opzioni di sostituzione.</p> &#9654&nbsp;Punteggi inclusi nel totale del team nella fase di qualifica<br> &#9655&nbsp;Punteggi non inclusi nel totale del team nella fase di qualifica';
$lang['GetBarcodeSeparator']='Dopo aver stampato la pagina con i riferimenti dei Codici a Barre, leggi con la pistola il codice a barre "SEPARATORE" in modo da attivare il corretto lettore';
$lang['HomePage']='Questa è la pagina dove puoi selezionare o creare un Torneo';
$lang['ISK-LockedSessionHelp']='L\'icona {$a} indica se la app può inserire o meno dei punteggi nella sessione';
$lang['ISK-ServerUrlPin']='<b>NON RIVELARE QUESTO NUMERO</b><br>Scegli un PIN (4 Cifre Numeriche) da usare per accedere alla tua competizione.<br>I Dispositivi potranno inviare punteggi alla tua gara solo leggendo il codice QR che viene stampata da IANSEO.<br> In caso di inserimento manuale dei dati di gana nella app Ianseo Scorekeeper LITE, Il codice competizione da usare è <b>{$a}</b>';
$lang['ScoreBarCodeShortcuts']='Leggi il Codice a Barre stampato sullo Score.
Inserendo # seguito dal nome di un atleta si cerca nel database questo atleta.
Inserendo @ seguita dal numero di piazzola si cerca nel database questa piazzola. La distanza DEVE essere specificata. La sessione può essere specificata (primo numero) e il numero della piazzola deve essere composto da 3 cifre';
$lang['TV-ChannelSetup']='<b>CONFIGURAZIONE DEI CANALI</b><br>
<br>
Dopo aver impostato i canali come si desiderano, collega il browser del dispositivo che vuoi collegare a un canale a <code>http://IP.DI.IANSEO/tv.php?Id=CANALE</code> dove <b>IP.DI.IANSEO</b> è l\'IP su cui è in esecuzione ianseo (inclusa la directory se presente) e <b>CANALE</b> \'è l\'ID del canale';
$lang['TV-RotEdit']='<div>Una pagina di presentazione è composta da almeno una pagina di contenuto.</div><div>Le pagine di contenuto verranno quindi mostrate una dopo l\'altra e ricominceranno daccapo.</div> <div><b> NOTA:</b> nei motori di versione normale e leggera, il primo contenuto viene nuovamente mostrato come ultimo, è quindi consigliabile inserire come primo contenuto un\'immagine (ad esempio il logo della competizione).</div> <div> I contenuti possono essere inerenti alla competizione (elenco piazzole, qualifiche, scontri...) oppure "multimediali" (immagini, messaggi HTML, ...).</div>';
$lang['TV-RotEdit-DB']='<h2>Gestione CSS3 (motore avanzato)</h2><h3>Unità di lunghezza</h3><ul><li><b>rem:</b> altezza del carattere principale</li><li><b>em:</b>altezza del carattere corrente</li><li><b>ex:</b>altezza della "x"minuscola</li><li><b>ch: </ b> larghezza del numero "0"</li><li><b>vh:</b>un centesimo dell\'altezza dello schermo</li><li><b>vw:</b> un centesimo della larghezza dello schermo</li><li><b>vmin:</b> un centesimo del valore minimo tra l\'altezza e la larghezza dello schermo</li><li><b>vmax:</b> un centesimo del valore massimo tra l\'altezza e la larghezza dello schermo</li></ul><h3> Box flessibili</h3><li><b>contrai ABC:</b><ul><li><b>A</b>: se 0 significa che la casella non può espandersi; se> 1 significa che la casella può espandersi a quella "velocità" rispetto ad altre caselle (se la casella 1 ha 2 e la casella 2 ha 3, la casella 2 si espanderà di 1,5 in più rispetto alla casella 1 che a sua volta si espanderà il doppio di una casella con questo valore impostato a 1)</li><li><b>B:</b> se 0 il box non può ridursi; se 1 il box può ridursi</li><li> <b>C:</b> dimensione iniziale del box</li></ul></li><h3>Riferimento CSS</h3><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Reference">https://developer.mozilla.org/en-US/docs/Web/CSS/Reference</a>';
$lang['TV-RotList']='<div>Questo è l\'elenco delle pagine di presentazione disponibili da inviare a maxischermi, monitor o broadcast.</div><div> Sono forniti 3 diversi motori, fare clic sul collegamento per attivarli:</div><ul><li>un normale motore compatibile con la maggior parte dei browser</li><li>una versione leggera del motore compatibile con la maggior parte dei browser ma che utilizza meno risorse</li><li>una versione avanzata che utilizza i browser moderni funzionalità HTML5</li></ul><div>Per creare un nuovo contenuto, inserisci un nome e premi il pulsante.</div>';
?>