<?php
$lang['Archery3SetsScores.qtz']='This layer creates an overlay with the running result of the match on the bottom top of the page. Manual or timed refresh of data coming from ianseo live event. It shows Total Set score and all previous set scores.';
$lang['Archery5SetsScores.qtz']='This layer creates an overlay with the running result of the match on the bottom top of the page. Manual or timed refresh of data coming from ianseo live event. It shows Total Set score and all previous set scores.';
$lang['ArcheryEventHeader.qtz']='This layer creates an overlay with the title of the match on the top of the page. Data come from Ianseo live event but needs manual refresh.';
$lang['ArcheryTeamScores.qtz']='Like Archery5SetsScores.qtz but for teams.';
$lang['ArcheryTopScoring.qtz']='Shows running result of a match in top left corner of the screen or full screen. It is possible to connect the archer\'s pictures or flag too. With set or cumulative score.';
$lang['BoinxLayer']='Boinx Layer';
$lang['BoinxSchedule']='[Boinx Layers Scheduler]';
$lang['Download']='Ladda ner';
$lang['HowToUse']='How to integrate Ianseo and Boinx';
$lang['Ianseo30.qtz']='A small animation to celebrate a great end.<br/>Same animation (with different arrows coming) for Perfect 20, 30, 40, 60.<br/>Different animation for 29, 39, 59.';
$lang['IanseoCrono.qtz']='Timing for alternate shooting matches. This layer requires a very fast computer not to loose the syncro. Stop one time will start the other one. Totally manual controlled. In the future it will take data from DoS Danage device.';
$lang['IanseoGrid.qtz']='[This layer shows the grid of the matches for the event selected. The starting phase is always 4th of finals.]';
$lang['IanseoMeteo.qtz']='This layer shows a page with different meteo data, e.g. direction and speed of the wind, temperature, umidity.<br/>Set up position and dimension. Data come from file boinxmeteo.xml and are generated by an appropriate device.';
$lang['IanseoStanding.qtz']='Layer for Award Ceremony. Medals and winner names (coming soon) directly from ianseo.';
$lang['IanseoTurn.qtz']='A small arrow that indicates archer or team that is currently shooting. Depends on Archery5SetScores.qtz. At the moment the control is fully manual.';
$lang['IanseoWind.qtz']='This layer overlays a small “wind rose” with direction and speed of the wind.<br/>Set up position and dimension. Data comes from file boinxmeteo.xml and are generated by an appropriate device.';
$lang['IanseoXToWin.qtz']='This layer creates an overlay that darkens the outer rings of the target bringing into attention the rings that the archer shoud hit to win the set/match.<br/>After the set up of the camera, set up also the layer to combine the virtual center with the real one, for both targets.';
$lang['ScheduleAwards']='Priscermoni';
$lang['ScheduleFeed']='RSS Feeds';
$lang['ScheduleGrids']='Stegar';
$lang['StepImportLayers']='Step $a: Import Boinx Layers';
$lang['StepImportLayersText']='From the table below, download and install in Boinx (Menu item is "File/Import Layer Composition") the layers you want to use.';
$lang['StepImportXML']='Step $a: Download Boinx Configuration File';
$lang['StepImportXMLText']='Before downloading the configuration file, be sure you are viewing this page from the computer running Boinx!<br/> From the table below, download the configuration file of the tournament you want to link and save it in your root directory. The name <b>must</b> be "$a".';
$lang['XMLConfiguration']='Configuration file';
?>